### ISSUE TITLE
Issue with Optifine

### ISSUE THREAD

**Issue by ghost** [suppergerrie2/PanoramaMod#1]
spanorama 1.1
Minecraft 1.14.4
Forge 28.2.1
Optifine 1.14.4 HD U F5

just a small bug. when using optifine all the panorama images come out the same.

**Comment by suppergerrie2** [comment]
Sadly I cant fix anything related with optifine due to optifine being closed source. 
Any bugs that cant be reproduced without optifine have to be reported to optifine as they are the cause.
